services:
  # backend:
  #   build: .
  #   depends_on:
  #     - mongodb
  #   volumes:
  #     - ./src:/src:ro
  #   restart: always
  #   extra_hosts:
  #       - "host.docker.internal:host-gateway"

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - db_volume:/data/db:rw
      - db_conf:/data/configdb
    restart: always

volumes:
  db_volume:
  db_conf:
